### ISSUE TITLE
Unexpected ClassCastException with "zeroOrMore" reduction rules

### ISSUE THREAD

**Issue by lebel-louisjacob** [sirthias/parboiled2#206] opened 2019-06-22 15:52 UTC
I am trying to parse my own language with parboiled.

[This line](https://github.com/exo-language/scala-compiler/blob/0d74962283d4c1d28608f49ad46baeea3e696f90/shared/src/test/scala/com/github/louisjl/shared/syntax/PartialReferenceToVolatileSpec.scala#L50) from a test for the parser implementation:
```
'': next.toString(in: in) in
```
fails to be parsed because [this rule](https://github.com/exo-language/scala-compiler/blob/0d74962283d4c1d28608f49ad46baeea3e696f90/shared/src/main/scala/com/github/louisjl/shared/parser/ExoParser.scala#L225) always throws a `ClassCastException`:
```
((TypeRule() ~ PartialObjectLiteral()) | ReferenceRule()) ~ (VolatileObjectLiteral() ~ AccessRule() | AccessRule()).+ ~ VolatileObjectLiteral()
```
when the parser __successfully matches it__.

Here is the log:
```log
java.lang.ClassCastException: class com.github.louisjl.shared.syntax.volatile.LiteralVolatileExpression cannot be cast to class com.github.louisjl.shared.syntax.PartialExpression (com.github.louisjl.shared.syntax.volatile.LiteralVolatileExpression and com.github.louisjl.shared.syntax.PartialExpression are in unnamed module of loader 'app')
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$VolatileObjectLiteral$4(ExoParser.scala:81)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$VolatileObjectForString$1(ExoParser.scala:219)
	at com.github.louisjl.shared.parser.ExoParser.rec$8(ExoParser.scala:213)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$StringRule$1(ExoParser.scala:212)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$2(ExoParser.scala:103)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$qmark$1(ExoParser.scala:336)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$4(ExoParser.scala:114)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$5(ExoParser.scala:123)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$6(ExoParser.scala:128)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectRule$1(ExoParser.scala:49)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$3(ExoParser.scala:109)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.rec$20(ExoParser.scala:328)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$plus$1(ExoParser.scala:327)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$times$1(ExoParser.scala:320)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$4(ExoParser.scala:114)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$5(ExoParser.scala:123)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$6(ExoParser.scala:128)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectRule$1(ExoParser.scala:49)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$3(ExoParser.scala:109)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.rec$20(ExoParser.scala:328)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$plus$1(ExoParser.scala:327)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$times$1(ExoParser.scala:320)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$4(ExoParser.scala:114)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$5(ExoParser.scala:123)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$6(ExoParser.scala:128)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectRule$1(ExoParser.scala:49)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$3(ExoParser.scala:109)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.rec$20(ExoParser.scala:328)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$plus$1(ExoParser.scala:327)
	at com.github.louisjl.shared.parser.ExoParser$CustomRule.$anonfun$$times$1(ExoParser.scala:320)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$4(ExoParser.scala:114)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$5(ExoParser.scala:123)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectLiteral$6(ExoParser.scala:128)
	at com.github.louisjl.shared.parser.ExoParser.$anonfun$PartialObjectRule$1(ExoParser.scala:49)
	at com.github.louisjl.shared.parser.ExoParser.PartialMain(ExoParser.scala:43)
	at com.github.louisjl.shared.parser.ExoParser$.$anonfun$parse$1(ExoParser.scala:16)
	at org.parboiled2.Parser.runRule$1(Parser.scala:143)
	at org.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151)
	at org.parboiled2.Parser.__run(Parser.scala:209)
	at com.github.louisjl.shared.parser.ExoParser$.parse(ExoParser.scala:16)
	at com.github.louisjl.shared.parser.ExoParser$.parseAsVolatile(ExoParser.scala:26)
	at com.github.louisjl.shared.syntax.PartialReferenceToVolatileSpec.$anonfun$new$2(PartialReferenceToVolatileSpec.scala:34)
        at ... [scalatest trace]
```

I will try to reproduce using a minimal code base soon: there is a lot of stuff in my project that is not required for the exception to show up. [This](https://gitlab.com/exo-language/exo-standard/wikis/home) might help for now.

**Comment by lebel-louisjacob** [comment] 2019-06-22 17:38
It should be possible right now for anyone to pull https://github.com/exo-language/scala-compiler/tree/extract-symbols-from-expressions and run the tests with `intellij` | `maven`

**Comment by lebel-louisjacob** [comment] 2019-06-24 04:02
Okay, so I successfully reproduced on 2.1.7:

```scala
object App {
    def main(args: Array[String]): Unit = {
        println(new ABParser("ab").Main.run().get)
    }
}

import org.parboiled2._
import shapeless._

trait A

trait B

case class B2A(b: B) extends A

case class A2B(a: A) extends B

class ABParser(override val input: ParserInput) extends Parser {
    def Main: Rule1[A] = rule {
        BRule ~ BReduction ~ B2ARule
    }

    private def BReduction: Rule[B :: HNil, B :: HNil] = rule {
        ((B2ACapture | B2ARule) ~ A2BCapture).*
    }

    private def BRule: Rule1[B] = rule {
        push(new B {})
    }

    private def B2ARule: Rule[B :: HNil, A :: HNil] = rule {
        MATCH ~> B2A
    }

    private def B2ACapture: Rule[B :: HNil, A :: HNil] = rule {
        str("a") ~> B2A
    }

    private def A2BCapture: Rule[A :: HNil, B :: HNil] = rule {
        str("b") ~> A2B
    }
}
```

This is the output of running the above app:
```
Exception in thread "main" java.lang.ClassCastException: B2A cannot be cast to B
	at ClassCastParser.B2ARule(ClassCastParser.scala:25)
	at ClassCastParser.Main(ClassCastParser.scala:14)
	at App$.$anonfun$main$1(App.scala:3)
	at org.parboiled2.Parser.runRule$1(Parser.scala:143)
	at org.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151)
	at org.parboiled2.Parser.__run(Parser.scala:209)
	at App$.main(App.scala:3)
	at App.main(App.scala)

Process finished with exit code 1
```

**Comment by lebel-louisjacob** [comment] 2019-06-24 04:07
I think the problem comes from the rule `BReduction`: the parser returns `A` at that point (accroding to my intellij's "watches" when debugging).

Is this a known bug?

**Comment by lebel-louisjacob** [comment] 2019-06-24 04:23
I made a repository here: https://github.com/lebel-louisjacob/parboiled2-2.1.7-class-cast-exception

**Comment by sirthias** [comment] 2019-06-24 12:05
This appears to be a duplicate of this bug: https://github.com/sirthias/parboiled2/issues/171
Here is the mailing list discussion for it: https://groups.google.com/forum/#!topic/parboiled-user/-d7X-LsCQqQ

**Comment by lebel-louisjacob** [comment] 2019-06-25 03:50
Closing as this is indeed a duplicate of #171 despite the fact that a side effect is generating the bug this time.

**Closed** 2019-06-25 03:50 UTC

**Comment by lebel-louisjacob** [comment] 2019-06-25 04:43
@sirthias Sorry to bother again in advance.

I'm not sure if this is in fact the same issue as #171, because changing
```scala
def BReduction: Rule[B :: HNil, B :: HNil] = rule {
    ((B2ACapture | B2ARule) ~ A2BCapture).*
}
```
to
```scala
def BReduction: Rule[B :: HNil, B :: HNil] = rule {
    (B2ACapture ~ A2BCapture | B2ARule ~ A2BCapture).*
}
```
still throws the same exception.

In intellij, the execution follows this order, in debug mode, with `"ab"` as input:

- _Input_: `"ab"`, _ValueStack_: `{ B }`
- `B2ACapture` : MATCH, _Input_: `"b"`, _ValueStack_: `{ B2A@156 }`
- `A2BCapture` : MATCH, _Input_: `""`, _ValueStack_: `{ A2B@167 }`
- **Note**: `(...).*` matched once, now trying to match more
- `B2ACapture` : FAIL, _Input_: `""`, _ValueStack_: `{ A2B@167 }`
- `B2ARule` : MATCH, _Input_: `""`, _ValueStack_: `{ B2A@173 }`
- `A2BCapture` : FAIL, _Input_: `""`, _ValueStack_: `{ B2A@173 }`
- **Note**: `(...).*` matched once and failed for further runs, now returning to "caller" rule (i.e. the rule that called `BReduction` (`Main` in this case))
- **Note**: here, the value stack is not reset (its head is still the unchanged `B2A@173` instead of the previously pushed `A2B@167`. Isn't this weird?).

I must be dumb or something, but I don't get in what this is related to #171. I don't get either what happens behind the scenes that invalidates the value stack in this code snippet. May you please provide a brief explanation for this?

**Comment by sirthias** [comment] 2019-06-25 07:53
In the expression 

```scala
B2ACapture ~ A2BCapture | B2ARule ~ A2BCapture
```

the `|` operator has higher precedence than the `~` operator.
However, the sub-expression `A2BCapture | B2ARule` is actually illegal, since it has no legal type!
You cannot have a rule that expects _either_ and `A` or a `B` at the top of the value stack.
You _could_ have a rule that expects an `Either[A, B]` on top of the value stack, but that's a different thing.

With #171 fixed this shouldn't compile.

**Comment by lebel-louisjacob** [comment] 2019-06-25 09:34
Okay, everything makes a lot more sense!

Overriding the precedence of the operators should then be solvable, in this case, by adding parentheses to the expression -- like the following:

```scala
(B2ACapture ~ A2BCapture) | (B2ARule ~ A2BCapture)
```
There should finally be no problem star-ing this expression, I think.

**Comment by lebel-louisjacob** [comment] 2019-06-25 09:35
I just tried adding parenthesis and I still end up with the same exception. In fact, this:
```scala
def BReduction: Rule[B :: HNil, B :: HNil] = rule {
    (BReductionLeft | BReductionRight).*
}

def BReductionLeft: Rule[B :: HNil, B :: HNil] = rule {
    B2ACapture ~ A2BCapture
}

def BReductionRight: Rule[B :: HNil, B :: HNil] = rule {
    B2ARule ~ A2BCapture
}
```
won't work either at runtime, and I don't see the precedence of operation interfering anywhere.

**Comment by sirthias** [comment] 2019-06-25 14:17
Well, your parser does indeed show a bug that hasn't been reported up to now, which is quite curious since it's actually quite severe.

I've just created #207 and a simplified test for it.
Hopefully the ticket description is understandable.

The reason you've tripped across this problem is that your parser setup is somewhat unorthodox, with the heavy in-place mutations of the value stack. My guess would be that reduction rules are normally used quite sparingly and only in "simple", more local contexts (as shown in the README), which is why nobody came across this bug up to now.

Anyway, thank you for reporting this!

**Comment by lebel-louisjacob** [comment] 2019-06-26 23:22
Alright! I'm glad I could could contribute to the the todo value stack. 🤘
